### ISSUE TITLE
multiple values for role user

### ISSUE THREAD

**Issue by webattitude** [gmontard/helioth#4]
Would it be possible/simple to let User model have multiple values for _user_ role ?

**Comment by gmontard** [comment]
That's an interesting idea, could you share you use case to see if it would fit the main purpose of this gem?

Thanks.

**Comment by webattitude** [comment]
Indeed, I'm not strictly following its main purpose.
We have an app with different main content types.
Each of our customers animates a community. Our customers may or may not have access to all content types, ie amongst a community, not all users may have access to content types one customer has purchased : managers choose users they want to grant access to one content type or another.

**Comment by gmontard** [comment]
I guess you should look for an authorization gem like CanCan for example.
Helioth is really not meant for this purpose even if it may seems it could.

**Comment by webattitude** [comment]
Ok, we're already using pundit, we'll go farther with it.

**Comment by webattitude** [comment]
thanks :)
